### ISSUE TITLE
Not accepting any API key

### ISSUE THREAD

**Issue by Sikksens** [Goksi/PteroBot#13]
Not sure if I have to do something specific to the API key, but doesn't seem to be accepting any of the 4 I created.
Tested with both read-only and read-write.

![image](https://user-images.githubusercontent.com/15923337/206874140-2385db76-901b-4a51-b222-1d12d6285aea.png)

**Comment by Sikksens** [comment]
I didn't even know that was a thing, thanks for the help :)

**Comment by Goksi** [comment]
Glad you made it work :)
